# Generated by Django 5.1.5 on 2025-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='time',
            field=models.TimeField(),
        ),
    ]
