# Generated by Django 5.1.5 on 2025-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_duration_alter_questionset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
